
---
AWSTemplateFormatVersion: "2010-09-09"
Description: cretae RDS in SQL 

Parameters:
  DBName:
    Default: MyDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: must contain only alphanumeric characters.
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '1024'
    ConstraintDescription: must be between 5 and 1024Gb.
  DBInstanceClass:
    Description: The database instance type
    Type: String
    Default: db.t2.small
  EC2SecurityGroup:
    Description: The EC2 security group that contains instances that need access to the database 
    Default: default
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-]+'
    ConstraintDescription: must be a valid security group name.
  #AlarmTopic:
    # Description: "SNS topic to notify if thee are operationla issues"
    #Type: "String"
  MultiAZ:
    Description: Multi-AZ master database
    Type: String
    Default: 'false'
  SnapshotOnDelete:
    Description: Do you want to create a Snapshot on instance delete?
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
Resources:
  DBEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    #Condition: Is-EC2-VPC
    Properties:
      GroupDescription: Open database for access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupName: !Ref EC2SecurityGroup
 # DBSecurityGroup:
  #  Type: AWS::RDS::DBSecurityGroup
   # #Condition: Is-EC2-Classic
    ##DBSecurityGroupIngress:
      #  EC2SecurityGroupName: !Ref EC2SecurityGroup
      #GroupDescription: database access
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      Engine: MySQL
      EngineVersion: 5.5
      DBSecurityGroups: !Ref DBSecurityGroup
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      MultiAZ: !Ref MultiAZ
    #DeletionPolicy: !Ref SnapshotOnDelete 

   



