AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template for create a vpc with a public subnet.'
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        -
          Key: Name
          Value: Demovpc
  Subnet:
    Type: AWS::EC2::Subnet 
    Properties:
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref Vpc

  RouteTable:
    Type: AWS::EC2::RouteTable 
    Properties:
      VpcId: !Ref Vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway
      
  Route:
    Type: AWS::EC2::Route 
    DependsOn:
      - GatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet

  WebServerInstance:
    Type: AWS::EC2::Instance 
    DependsOn:
      - Route
      - SubnetRouteTableAssociation
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref Subnet 
      ImageId: ami-005f9685cb30f234b
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup 
    Properties:
      GroupDescription: security group 
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        -
          IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0 

